import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "../api";
import { useAuth } from "../context/AuthContext";

/**
 * "Recommended for You" — the rule-based list from RecommendationService.
 *
 * Each card carries its own `why`, generated by the same code that awarded the
 * points, so the reason shown can never disagree with the ranking.
 */
export default function RecommendedArticles({ exclude, limit = 3 }) {
  const { token } = useAuth();
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let live = true;
    setLoading(true);
    api
      .getRecommendedArticles(token, { limit, exclude })
      .then((data) => live && setItems(data))
      // A failed recommendation list is not worth an error banner — the
      // section simply does not render.
      .catch(() => live && setItems([]))
      .finally(() => live && setLoading(false));
    return () => {
      live = false;
    };
  }, [token, exclude, limit]);

  if (loading || items.length === 0) return null;

  return (
    <section className="rd-recs">
      <div className="rd-sec-head">
        <h2 className="rd-sec-title">Recommended for You</h2>
      </div>

      <div className="rd-rec-grid">
        {items.map((a) => (
          <Link key={a.id} className="rd-rec" to={`/read/${a.id}`}>
            <span className="rd-rec-thumb">
              {a.image_url ? (
                <img src={a.image_url} alt="" />
              ) : (
                <span className="rd-rec-ph" />
              )}
              {a.already_read && <span className="rd-rec-read">Read</span>}
            </span>

            <span className="rd-rec-body">
              <span className="rd-rec-tags">
                {a.hsk_level && (
                  <span className="rd-chip rd-chip-level">{a.hsk_level}</span>
                )}
                {a.tags?.slice(0, 2).map((t) => (
                  <span key={t.kind + t.value} className="rd-chip">
                    {t.value}
                  </span>
                ))}
              </span>

              <span className="rd-rec-title">{a.title}</span>
              <span className="rd-rec-why">{a.why}</span>

              <span className="rd-rec-foot">
                {a.reading_minutes} min read
                <span className="rd-rec-cta">Read article</span>
              </span>
            </span>
          </Link>
        ))}
      </div>
    </section>
  );
}
