<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up()
    {
        Schema::table('messages', function (Blueprint $table) {
            /* A retry must resolve to the original saved row, never publish a
               second copy of the same message. The id is generated by the
               client only for reconciliation; sender identity stays server-side. */
            $table->string('client_id', 64)->nullable()->after('sender_id');
            $table->unique(['conversation_id', 'sender_id', 'client_id'], 'messages_client_id_unique');
        });
    }

    public function down()
    {
        Schema::table('messages', function (Blueprint $table) {
            $table->dropUnique('messages_client_id_unique');
            $table->dropColumn('client_id');
        });
    }
};
