import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { api } from '../api'
import './Upgrade.css'

const FREE_FEATURES = ['15 monthly Chinese text scans', 'Access to free stories', 'Access to free podcasts', 'Basic vocabulary practice', 'Tutor discovery and booking']
const PRO_FEATURES = ['100 monthly Chinese text scans', 'Full story library and premium transcripts', 'Expanded full-text translation', 'Gemini practice assistant allowance', 'Ad-free learning']

export default function Upgrade() {
  const { user, token } = useAuth(); const [status, setStatus] = useState(null); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState('')
  const refresh = () => api.getSubscriptionStatus(token).then(setStatus).catch(() => setNotice('We could not load subscription details. Please try again.'))
  useEffect(() => { if (token) refresh() }, [token]) // eslint-disable-line react-hooks/exhaustive-deps
  const startCheckout = async () => { setBusy(true); setNotice(''); try { const result = await api.createSubscriptionCheckout(token); window.location.assign(result.url) } catch (e) { setNotice(e.message || 'Checkout could not be started.') } finally { setBusy(false) } }
  const manage = async () => { setBusy(true); try { const result = await api.createSubscriptionPortal(token); window.location.assign(result.url) } catch (e) { setNotice(e.message || 'Billing management is unavailable.') } finally { setBusy(false) } }
  const renewal = status?.renewal_date ? new Date(status.renewal_date).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' }) : null
  const hasPro = status?.is_pro
  return <div className="up"><header className="up-head"><h1 className="up-title">Upgrade to Verbo Pro</h1><p className="up-lede">Unlock more ways to learn Chinese, practise naturally, and stay focused.</p></header>
    <div className="up-plans"><section className="up-card up-free"><header className="up-card-head"><h2 className="up-plan-name">Free</h2><p className="up-plan-sub">Start learning Chinese with essential Verbo tools.</p></header><p className="up-price"><span className="up-currency">$</span><span className="up-amount">0</span><span className="up-per">/ month</span></p><p className="up-price-note">Free forever</p><ul className="up-features">{FREE_FEATURES.map(f => <li key={f}><span className="up-tick">✓</span><span>{f}</span></li>)}</ul><button className="up-btn up-btn-quiet" disabled>Current plan</button></section>
      <section className="up-card up-pro"><span className="up-badge">PRO</span><header className="up-card-head"><h2 className="up-plan-name">Pro</h2><p className="up-plan-sub">Get the complete Verbo learning experience.</p></header><p className="up-price"><span className="up-currency">{status?.price?.currency?.toUpperCase() === 'USD' ? '$' : ''}</span><span className="up-amount">{status?.price?.monthly_display?.replace(/\s\/ month$/, '').replace(/^\$/, '') || '—'}</span><span className="up-per">/ month</span></p><p className="up-price-note">Billed monthly · cancel any time</p><ul className="up-features">{PRO_FEATURES.map(f => <li key={f}><span className="up-tick">✓</span><span>{f}</span></li>)}</ul>{hasPro ? <><button className="up-btn up-btn-primary" onClick={manage} disabled={busy}>Manage subscription</button><p className="up-notice">{status.status === 'past_due' ? 'Payment needs attention.' : `Pro is active${renewal ? ` through ${renewal}` : ''}.`}{status.cancel_at_period_end && renewal ? ` Pro remains available until ${renewal}.` : ''}</p></> : <button className="up-btn up-btn-primary" onClick={startCheckout} disabled={busy || !status?.price}>{busy ? 'Opening checkout…' : 'Start Verbo Pro'}</button>}{notice && <p className="up-notice" role="status">{notice}</p>}</section></div>
    <section className="up-section"><h2 className="up-section-title">What Pro changes</h2><div className="up-benefits">{['More practice','Premium reading','Premium podcasts','Focused learning'].map((title, i) => <article className="up-benefit" key={title}><span className="up-benefit-mark">{['✦','▤','◉','⊘'][i]}</span><h3 className="up-benefit-title">{title}</h3><p className="up-benefit-body">{PRO_FEATURES[i]}</p></article>)}</div></section>
    <footer className="up-fine"><p>Cancel any time. Your subscription renews automatically unless cancelled before the renewal date. Prices are shown in USD.</p><p>Questions about billing? <Link to="/settings">Open settings</Link>{user?.email ? ` · signed in as ${user.email}` : ''}</p></footer></div>
}
